# Generated by Django 4.1.1 on 2022-09-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='isActivo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='famipaciente',
            name='isActivo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='isActivo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.CharField(max_length=250, null=True, verbose_name='diagnostico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaIngreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaSalida',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='isActivo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='frecuenciaCardiaca',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='frecuenciaRespiratoria',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='isActivo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='presionArterial',
            field=models.CharField(max_length=50, null=True, verbose_name='presion'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='temperatura',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=200, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=0, null=True, verbose_name='Numero celular'),
        ),
    ]
