# Generated by Django 4.1.1 on 2022-09-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitApp', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='isActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='isActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.FloatField(default=0, null=True, verbose_name='Numero celular'),
        ),
    ]
