from .PacienteCrearVista import PacienteCrearVista
from .pacienteDetalleVista import PacienteDetalleVista
from .AuxiliarCrearVista import AuxiliarCrearVista
from .AuxiliarDetalleVista import AuxiliarDetalleVista
from .familiarCrearVista import FamiliarCrearVista
from .familiarDetalleVista import FamiliarDetalleVista
from .medicoCrearVista import MedicoCrearVista
from .medicoDetalleVista import MedicoDetalleVista
